name: Create GitHub release
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    container: ghcr.io/ombra-chat/builder:v0.0.2
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            platform: amd64
          - os: ubuntu-22.04-arm
            platform: arm64

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
        path: ombra-chat

      - name: Checkout tdlib-rs repo
        uses: actions/checkout@v4
        repository: https://github.com/ombra-chat/tdlib-rs.git
        path: tdlib-rs

      - name: Build ombra-chat
        run: cd ombra-chat && npm install && npm run tauri build

      - name: Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          files:
            - ombra-chat/src-tauri/target/release/bundle/deb/ombra-chat*.deb
            - ombra-chat/src-tauri/target/release/bundle/rpm/ombra-chat*.rpm
            - ombra-chat/src-tauri/target/release/bundle/appimage/ombra-chat*.AppImage
