name: Create GitHub release
on:
  push:
    tags:
      - '*'

env:
  TDLIB_VERSION: 1.8.47

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            platform: amd64
          - os: ubuntu-22.04-arm
            platform: arm64

    steps:
      - uses: actions/checkout@v4

      - name: Download tdlib.jar
        run: wget https://github.com/ombra-chat/tdlib-java/releases/download/v${TDLIB_VERSION}/tdlib-v${TDLIB_VERSION}.jar

      - name: Download libtdjni.so
        run: wget https://github.com/ombra-chat/tdlib-java/releases/download/v${TDLIB_VERSION}/libtdjni-v${TDLIB_VERSION}-${{ matrix.platform }}.zip

      - name: Unzip libtdjni.so
        run: unzip libtdjni-v${TDLIB_VERSION}-${{ matrix.platform }}.zip

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install tdlib to local maven repo
        run: mvn install:install-file -Dfile=tdlib-v${TDLIB_VERSION}.jar -DgroupId=org.drinkless -DartifactId=tdlib -Dversion=${TDLIB_VERSION} -Dpackaging=jar

      - run: mvn clean package

      - name: workaround for missing imageio-webp module-info #1
        run: cp lib/module-info.java ~/.m2/repository/com/twelvemonkeys/imageio/imageio-webp/3.12.0

      - name: workaround for missing imageio-webp module-info #2
        run: |
          cd ~/.m2/repository/com/twelvemonkeys/imageio/imageio-webp/3.12.0
          javac --patch-module com.twelvemonkeys.imageio.webp=imageio-webp-3.12.0.jar module-info.java

      - name: workaround for missing imageio-webp module-info #3
        run: |
          cd ~/.m2/repository/com/twelvemonkeys/imageio/imageio-webp/3.12.0
          jar uf imageio-webp-3.12.0.jar module-info.class

      - name: Create package
        run: mvn clean javafx:jlink

      - name: Copy libtdjni.so
        run: cp libtdjni.so target/ombrachat/lib/libtdjni.so

      - run: mv target/ombrachat .

      - name: Zip
        run: zip -r ombra-chat-${{ github.ref_name }}-${{ matrix.platform }}.zip ombrachat

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ombra-chat-${{ github.ref_name }}-${{ matrix.platform }}.zip
