name: Create GitHub release
on:
  push:
    tags:
      - '*'

env:
  TDLIB_VERSION: v1.8.47

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            platform: amd64

    steps:
      - uses: actions/checkout@v4

      - name: Download tdlib.jar
        run: wget https://github.com/ombra-chat/tdlib-java/releases/download/${TDLIB_VERSION}/tdlib-${TDLIB_VERSION}.jar

      - name: Download libtdjni.so
        run: wget https://github.com/ombra-chat/tdlib-java/releases/download/${TDLIB_VERSION}/libtdjni-${TDLIB_VERSION}-${{ matrix.platform }}.zip

      - name: Unzip libtdjni.so
        run: unzip libtdjni-${TDLIB_VERSION}-${{ matrix.platform }}.zip

      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Create package
        run: mvn clean javafx:jlink

      - name: Copy libtdjni.so
        run: cp libtdjni.so target/ombrachat/lib/libtdjni.so

      - run: mv target/ombrachat .

      - name: Zip
        run: zip -r ombra-chat-${{ github.ref_name }}-${{ matrix.platform }}.zip ombrachat

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ombra-chat-${{ github.ref_name }}-${{ matrix.platform }}.zip
